### ISSUE TITLE
Add Number operations

### ISSUE THREAD

**Issue by leafac** [JHU-PL-Lab/big-bang#19]
Implement:
- [ ] `>`.
- [ ] `<=`.
- [ ] `>=`.
- [ ] `/` (requires exceptions, due to division by zero, see #31).

~~In terms of `=` and `<`.~~

**Comment by zepalmer** [comment]
Why in terms of those other operations?  Those should be TinyBang primitives, really.  I suppose we could get away with implementing them in terms of the others for now if you're looking for a short-term solution.

**Comment by leafac** [comment]
I thought we would prefer to do this in order to keep the core (Tiny Bang) small.

**Comment by zepalmer** [comment]
Sadly, built-in arithmetic operations always bloat things.  There are a few reasons to include these built-ins in TinyBang:
- It prevents any particular operation (e.g. `<`) from being privileged.
- The result of TinyBang's typechecker should eventually be funneled to a compiler, which should be in a good position to use machine instructions for e.g. `>=`.
- When we get to operator overloading, it might not make sense to define one in terms of the other (such as in the case of partial orders).

Thankfully, the built-in framework simplifies the addition of these new operators and prevents them from having a dramatic effect on the complexity of the typechecker.  Unfortunately, it still means the associated engineering work.
